apiVersion: v1
kind: Service
metadata:
  name: warroom-api
  namespace: con-warroom
  labels:
    app: warroom-api
spec:
  type: ClusterIP
  selector:
    app: warroom-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
